

spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: user
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true
    encoding: UTF-8
    view-names: thymeleaf/*

mybatis:
  # resources/mapper/ ? ?? ?? xml ??
  mapper-locations: mapper/*.xml
  configuration:
    cache-enabled: true
    use-generated-keys: false
    default-executor-type: reuse
    call-setters-on-nulls: true
    default-statement-timeout: 65
    jdbc-type-for-null: null
    local-cache-scope: statement
    map-underscore-to-camel-case: true
  type-aliases-package: kr.co.uplus.mvas.model